name: test plugin example

on:
  workflow_run:
    workflows: ["release"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      logs:
        description: 'Set 1 to activate full logs'
        required: false
        default: '0'

jobs:
  build:
    runs-on: ubuntu-latest
    name: init and build example
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Init
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./example
          command: init

      - name: Validate
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./example
          command: validate
        env:
          PACKER_LOG: ${{ github.event.inputs.logs }}
          KAMATERA_API_CLIENT_ID: ${{ secrets.KAMATERA_API_CLIENT_ID }}
          KAMATERA_API_SECRET: ${{ secrets.KAMATERA_API_SECRET }}

      - name: Build
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: ./example
          command: build
        env:
          PACKER_LOG: ${{ github.event.inputs.logs }}
          KAMATERA_API_CLIENT_ID: ${{ secrets.KAMATERA_API_CLIENT_ID }}
          KAMATERA_API_SECRET: ${{ secrets.KAMATERA_API_SECRET }}
